### ISSUE TITLE
Illegal division by zero if the gapfile is empty

### ISSUE THREAD

**Issue by winem** [iamcheko/check_cpu_usage#4]
We ran out of disk space on one of our servers which caused an empty gapfile. 

The empty gapfile crashed the plugin with the following error message: Illegal division by zero at ./check_cpu_usage line 138.

**Comment by iamcheko** [comment]
I added some code to prevent a division by zerro.

**Comment by iamcheko** [comment]
Oh, I have seen that you provided a solution. Thanks for that.
